-- MySQL Script generated by MySQL Workbench
-- Tue Oct 20 19:39:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema truckappdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema truckappdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `truckappdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `truckappdb` ;

-- -----------------------------------------------------
-- Table `truckappdb`.`dc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `truckappdb`.`dc` ;

CREATE TABLE IF NOT EXISTS `truckappdb`.`dc` (
  `dc_number` INT(11) NOT NULL,
  `dc_city` VARCHAR(255) NULL DEFAULT NULL,
  `dc_type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`dc_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `truckappdb`.`dcslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `truckappdb`.`dcslots` ;

CREATE TABLE IF NOT EXISTS `truckappdb`.`dcslots` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dc_number` INT(11) NULL DEFAULT NULL,
  `max_trucks` INT(11) NOT NULL,
  `time_slots` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dc_number` (`dc_number` ASC) VISIBLE,
  CONSTRAINT `dc_number`
    FOREIGN KEY (`dc_number`)
    REFERENCES `truckappdb`.`dc` (`dc_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `truckappdb`.`truck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `truckappdb`.`truck` ;

CREATE TABLE IF NOT EXISTS `truckappdb`.`truck` (
  `truck_id` INT(11) NOT NULL AUTO_INCREMENT,
  `truck_number` BIGINT(20) NOT NULL,
  `truck_name` VARCHAR(255) NULL DEFAULT NULL,
  `truck_type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`truck_id`, `truck_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
